# -*- coding: utf-8 -*- 
{
	'name': 'Dincel Payroll',
	'version': '1.01',
	'website': 'https://www.dincel.com.au',
	'category': 'Payroll',
	'author':'Shukra Rai',
	'summary': 'Payroll, Single Touch Payroll',
	'description':'Dincel Payroll',
	'depends': ['account', 'hr', 'project', 'sale_timesheet', 'hr_timesheet', 'analytic', 'account_fiscalyear', 'hr_holidays', 'dincelaccount'], #for referencing in many2one relationship
	'data': [
		'views/payroll_config.xml',
		'views/payroll_views.xml',
		'views/timesheet_views.xml',
		'views/timesheet_pay_view.xml',
		'views/payroll_employee.xml',
		'views/payroll_reports.xml',
		'views/payroll_aba.xml',
		'views/hr_holidays.xml',
		'winwizard/timesheet_import.xml',
		'winwizard/payroll_generate.xml',
		'winwizard/payroll_generate_aba.xml',
		'winwizard/timesheet_import_new.xml',
		'winwizard/payroll_generate_queue.xml',
		'winwizard/payslip_manage.xml',
		'winwizard/timesheet_manage.xml',
		'winwizard/timesheet2payslip.xml',
		'report/layouts.xml',
		'report/report_data.xml',
		'report/report_leaves.xml',
		'report/report_payroll.xml',
		'report/report_leavesummary.xml',
		'report/report_leavesummary_all.xml',
		'report/report_leavedetails.xml',
		'report/report_defaultpage.xml',
		'report/report_payslip.xml',
		'report/report_payg_summary.xml',
		'report/report_payroll_summary.xml',
		'report/report_payroll_register_summary.xml',
		'report/report_payroll_super_summary.xml',
		'report/report_payroll_entries.xml',
		'report/report_payslip_all.xml',
		'report/dincelreport_template.xml',
		'report/report_opening_balance.xml',
		'report/report_employee_details.xml', 
		'report/report_payg_summary_annual.xml', 
		'views/payroll_menuitem_views.xml',
	],
	'css': ['static/src/css/style.css'],
	'installable': True,
	'auto_install': False,
}
